---
title: "Neovim as IDE"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Neovim as IDE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{css echo=FALSE}
img {
    border: 0px !important;
    margin: 2em 2em 2em 2em !important;
}
code {
    border: 0px !important;
}
kbd {
    background-color: #eee;
    border-radius: 3px;
    border: 1px solid #b4b4b4;
    box-shadow: 0 1px 1px rgba(0, 0, 0, .2), 0 2px 0 0 rgba(255, 255, 255, .7) inset;
    color: #333;
    display: inline-block;
    font-size: .85em;
    font-weight: 700;
    line-height: 1;
    padding: 2px 4px;
    white-space: nowrap;
}
```

```{r echo=FALSE, results="hide"}
knitr::opts_chunk$set(
    cache = FALSE,
    echo = TRUE,
    collapse = TRUE,
    comment = "#>"
)
```

## Making R and Python available by default

There are certain tools that we expect to use often but that are only available
to load via modules. For instance, we are likely to very often make use of R,
python, a compiler (GCC), or an editor (Neovim).

When we connect to the computing cluster, we open a shell, i.e. the command-line
interface there. The default for this is `bash`, which is usually available on
all Unix-like systems. (However, it is no longer default on macOS in favor of
`zsh`.)

Every time we start `bash` on the login node, it runs its configuration file,
`~/.bashrc`. To automatically load our standard tool set when we connect, we can
add the `module load` commands to this file:

```{sh eval=FALSE}
# User specific aliases and functions

if ! command -v R >/dev/null 2>&1; then
    module load GCC/11.2.0 OpenMPI/4.1.1 R/4.1.2
    module load GCCcore/11.2.0 Python/3.9.6 CMake/3.21.1
    module load Neovim/0.6.1
fi
```

After we edited this file, we can either close the connection and reconnect, or
type `source ~/.bashrc` to reload it. Note, however, that loading these modules
will result in a bit of a slowdown to establish the connection to the login
node. This may not be what you want for normal use, but it will simplify working
on the rest of the course materials.

We can also change some other things, like adding colors to the prompt and have
it display the current directory instead of just the folder name:

```{sh eval=FALSE}
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h\[\e[1;31m\](sulis)\[\e[0m\]:\[\033[33;1m\]\w\[\033[m\]\$ "
```

And add some useful aliases to make listing files and navigating between
different directories a bit easier:

```{sh eval=FALSE}
alias l='ls -lh'
alias ll='ls -lah'
alias .='pwd'
alias cd..='cd ..'
alias ..='cd ..'
alias ...=' cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
```

## Editing R scripts using Neovim

#### Configuration

For this, we edit the file `~/.config/nvim/init.vim` (create the directory
first using `mkdir -p`) to include:

```{vim eval=FALSE}
set expandtab       " tab as spaces (optional)
set shiftwidth=4    " shift by 4 spaces
set tabstop=4       " tab by 4 spaces
set smarttab        " tab to same positions
set autoindent      " automatic indentation
set mouse=a         " be able to use mouse clicks

set nobackup        " use an undo file instead of backup files
set undofile
set undodir=~/.config/nvim/undo

"colorscheme wombat " uncomment this after installing the plugin

" uncomment after installing Nvim-R
"let g:R_assign = 0 " do (not) map _ to <- for assignment
"let g:R_cmd = "srun --account su105 --pty R"
"vmap <Space> <Plug>RDSendSelection " use <Space> key to send a selection to R
"nmap <Space> <Plug>RDSendLine      " use <Space> key to send a line to R
```

#### Plugins

(Neo)vim and emacs are powerful editors that have many useful functions not only
for text editing, but also interactive development in R and other languages.

The functionality for this is provided by plugins. For emacs this is mainly ESS
(emacs speaks statistics), and for nvim we use the plugin manager `plug`, that
we can install using the following lines of code:

```{sh eval=FALSE}
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```

This will copy the file `plug.vim` from Github into your
*~/.local/share/nvim/site/autoload* directory.

*Note:* before executing bits of code from the internet, make sure they are from
trustworthy sources. In this case, it comes from the
[nvim-plug](https://github.com/junegunn/vim-plug) Github repository, which is
the official source.

We will add the following plugins:

* Nvim-R
* YouCompleteMe
* Wombat color scheme

For this, we add to the file `~/.config/nvim/init.vim`:

```{vim eval=FALSE}
call plug#begin()
    Plug 'sheerun/vim-wombat-scheme'
    Plug 'jalvesaq/Nvim-R'
    Plug 'ycm-core/YouCompleteMe', { 'do': './install.py' }
call plug#end()
```

Note that we need Python and `pynvim` for this to work:

```{sh eval=FALSE}
module load GCCcore/11.2.0 Python/3.9.6 CMake/3.21.1
pip install --user pynvim
```

We can then install the plugins in Neovim using <kbd>Esc</kbd> and:

```{vim eval=FALSE}
:PlugInstall
```

#### Using R within nvim

Uncomment the lines previously commented in `~/.config/nvim/init.vim`.

Using the `Nvim-R` plugin, we can access R directly from nvim. For this, we can
open any `.r` file, and then type <kbd>\\</kbd><kbd>r</kbd><kbd>f</kbd>.

We can now edit the file in the editor as we did before, but in addition send
lines to R via <kbd>Space</kbd>, or is the terminal directly by selecting it
with the mouse (or <kbd>Ctrl</kbd>+<kbd>w</kbd> followed by arrow keys).

Because we added an `srun` to the `R_app`, we can edit files on the login node,
but if we start up R this way the actual computations will be run in an
interactive job.

## Persistent sessions with `tmux`

So far, we have created a new terminal session each time we connected to the
login node. There are cases where we may instead want to continue to work where
we left off previously. There are tools that create a "persistent" session on
the login node that we can disconnect from and later connect to without losing
our work session. A well-known tool for this is `screen`, but more recently
there is `tmux`. `tmux` is installed on the login node, so we can use it out of
the box by typing:

```{sh eval=FALSE}
tmux new
```

On a first view, not much has changed. In addition to our normal terminal
prompt, there is now a status line at the bottom of the screen. We can now
perform some operations, like typing `ls` and `pwd`. When we want to disconnect,
we can use the keys <kbd>Ctrl</kbd>+<kbd>b</kbd>, <kbd>d</kbd> or type:

```{sh eval=FALSE}
tmux detach
```

This will close the `tmux` session. We can now disconnect from the login node,
later reconnect, and re-attach to the same session by typing:

```{sh eval=FALSE}
tmux attach -t 0
```

`0` in this case the the (automatic) name of the session we created previously.
In addition, we can also split our terminal in 2 vertical "panes" using
<kbd>Ctrl</kbd>+<kbd>b</kbd>, <kbd>%</kbd> or create a new "window" using
<kbd>Ctrl</kbd>+<kbd>b</kbd>, <kbd>c</kbd>. The panes, windows, and open
applications (e.g. a text editor) will be waiting for us each time we detach and
re-attach to the session. <kbd>Ctrl</kbd>+<kbd>b</kbd> is the common prefix, to
be typed before any other tmux command.

#### An `ssht` alias to automatically connect to tmux

We can define the following function to automatically connect to (or create) a
`tmux` session when we type `ssht sulis` instead of `ssh sulis`. If we are using
the `bash` shell locally as well, we can add these lines to our _local_
`~/.bashrc`:

```{sh eval=FALSE}
ssht() {
    ssh -t "$1" 'tmux -2 -u attach || tmux -2 -u new'
}
```

#### Making `tmux` easier to use

There are are a lot of different commands to remember, especially when first
starting to use `tmux`. We can add some configuration options in `~/.tmux.conf`
to make using it a bit more intuitive:

```{sh eval=FALSE}
## enable Ctrl+a as prefix for people used to "screen"
#set -g prefix C-a
#bind C-a send-prefix
#unbind C-b

# enable mouse clicks to select windows and panes
set -g mouse on

# easy-to-remember split pane commands
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# swap current pane with the next/previous one
bind > swap-pane -D
bind < swap-pane -U
```
